# This Service manifest defines:
# - a load balancer for pods matching label "app: python-hello-world"
# - exposing the application to the public Internet (type:LoadBalancer)
# - routes port 80 of the load balancer to the port 8080 of the Pods.
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: image-segmentation-external
spec:
  type: LoadBalancer
  selector:
    app: image-segmentation
  ports:
  - name: http
    port: 80
    targetPort: 8501
